sonar.projectKey=tnap.SONAR.portal-ui
sonar.projectName=portal-ui
sonar.projectDescription="UI Part of Team Tesla's Portal"


# Scan settings.
sonar.projectBaseDir=.
sonar.java.binaries=.

#Comma-separated paths to directories containing the compiled bytecode files corresponding to your test files
#sonar.java.libraries=

#Comma-separated paths to files with third-party libraries (JAR or Zip files) used by your project. Wildcards can be used:
sonar.sources=./src

# Define the directories that should be scanned. Comma separated.
#sonar.sourceEncoding=UTF-8

#sonar.exclusions=,**/coverage/**
sonar.exclusions=**/node_modules/**, **/*.css, openapi/**, src/app/modules/dashboard/**/*, src/app/modules/service-models-deployment/**/*, src/app/modules/cell-site-map/**/*, src/app/modules/alarm/**/*,\
src/app/modules/kpi-dashboard/**/*, src/app/modules/ru-management/**/*, src/app/modules/service-instance-list/**/*, src/app/modules/sw-management/**/*, e2e/**,\
playwright/**, playwright.config.ts, src/environments/**, Dockerfile

sonar.cpd.exclusions=src/assets/**/*, src/app/components/layout/**/*, src/support/**/*, **/configuration.ts, e2e/**, playwright/**, playwright.config.ts, src/environments/**, Dockerfile, src/app/modules/policies/policy-help/**/*.html,\
src/app/modules/cm-action/cm-action-columns.config.ts

sonar.coverage.exclusions=karma.conf.js,e2e/**,src/assets/*,eslint.config.mjs, playwright/**, playwright.config.ts, src/environments/**, Dockerfile

sonar.issue.ignore.multicriteria=e1,e2,e3,e4,e5,e6
sonar.issue.ignore.multicriteria.e1.ruleKey=Web:ItemTagNotWithinContainerTagCheck
sonar.issue.ignore.multicriteria.e1.resourceKey=**/collapsible-menu-item.component.html

sonar.issue.ignore.multicriteria.e2.ruleKey=Web:ItemTagNotWithinContainerTagCheck
sonar.issue.ignore.multicriteria.e2.resourceKey=**/menu-item.component.html

sonar.issue.ignore.multicriteria.e3.ruleKey=typescript:S7648
sonar.issue.ignore.multicriteria.e3.resourceKey=**/*

sonar.issue.ignore.multicriteria.e4.ruleKey=typescript:S6268
sonar.issue.ignore.multicriteria.e4.resourceKey=**/sanitizeUrl.pipe.ts

sonar.issue.ignore.multicriteria.e5.ruleKey=typescript:S5852
sonar.issue.ignore.multicriteria.e5.resourceKey=**/*

sonar.issue.ignore.multicriteria.e6.ruleKey=typescript:S2245
sonar.issue.ignore.multicriteria.e6.resourceKey=**/*

sonar.dependencyCheck.skip=true

# Fail CI pipeline if Sonar fails.
sonar.qualitygate.wait=true

# Comma-delimited list of test file path patterns to be included in analysis. When set, only test files matching
# the paths set here will be included in analysis.
sonar.test.inclusions=**/*.spec.ts

# Comma-delimited list of paths to LCOV coverage report files. Paths may be absolute or relative to project root.
sonar.typescript.lcov.reportPaths=coverage/lcov.info
